### ISSUE TITLE
Newb question

### ISSUE THREAD

**Issue by 7MinSec** [l0ss/Grouper#15]
Hey there,

Thanks for this tool, I'm really excited about it but, at the same time, not entirely sure how to interpret some of the results.  I ran this against a company's GPO XML export (using level 3) and the results were:

````
Get-GPOUserRights - All Policy
##############################

Name                           Value
----                           -----
Right                          SeMachineAccountPrivilege
Members                        NT AUTHORITY\Authenticated Users
````
I believe this interprets as "any authenticated user can join computers to the domain" - is that right?  It would be awesome to have some context around the findings, like a default blurb of "Hey, this setting sometimes means X so you should check Y and Z."  

Side note: I'm happy to provide such a blurb if that would be helpful.  And also, this is the only time I've run Grouper so maybe the other findings have more verbose info in them?

**Comment by l0ss** [comment]
Hi braimtree,

Yep, that's exactly what it means. The blurb type thing you describe is definitely one of the things on my TODO list, so if you felt like contributing some words that would be appreciated.

Cheers!
