### ISSUE TITLE
Powershell parsing errors

### ISSUE THREAD

**Issue by Raikia** [l0ss/Grouper#5]
Thanks for releasing this, it looks like there are some errors with displaying the banner though:

![asdf](https://i.imgur.com/WwTtRUo.png)

**Comment by l0ss** [comment]
What version of Windows/PS are you on? I do my testing on 2012R2 and 2016.

**Comment by Raikia** [comment]
Windows 7 and PowerShell version 2

**Comment by l0ss** [comment]
OK, i'll have to spin up a Win7 VM and test.

**Comment by l0ss** [comment]
I've figured out how to fix the banner but oddly enough under Win7 I don't get any output.

It'll take some time to figure out why.

**Comment by l0ss** [comment]
Oh dear, it appears that the way PS handles System.Xml.XmlElement objects has changed substantially at some point and Grouper relies heavily on the new behaviour.

I'll add Win7/PS 2.0 compatibility to my TODO list but in the meantime let's just say you need to use newer Windows/PS.

**Comment by Raikia** [comment]
Yeah, honestly I think that's acceptable to just ignore it since you can export the XML and put it on an updated VM or something.  Thanks for letting me know!  I'd recommend throwing that into the README or printing an error or something if it detects its running on PS2
