### ISSUE TITLE
The specified module 'grouper.ps1' was not loaded because no valid module file was found in any module directory

### ISSUE THREAD

**Issue by mxm0z** [l0ss/Grouper#6]
I couldn't do the Import-Module command. I generated the report on my AD Server and I tested on my own computer. It appeared the following error:

The specified module 'grouper.ps1' was not loaded because no valid module file was found in any module directory.
Line: 1 Character:14
+ CategoryInfo          : ResourceUnavailable: <grouper.ps1:String> [Import-Module], FileNotFoundException
+ FullQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PoweShell.Commands.ImportModuleCommand

My system: Windows 7 Pro x64

I also tested the importing on the AD Server Powershell Terminal and I got the same error. The only difference was that:
...
Line: 1 Character:1
...

My AD Server system: Windows Server 2012 R2 Standard

**Comment by l0ss** [comment]
It looks like you've done
```
Import-Module grouper.ps1
```
which doesn't tell PS where to find the module file. If it's in the current working directory, you need to do:
```
Import-Module .\grouper.ps1
```
otherwise you'll have to tell it the full path:
```
Import-Module C:\users\administrator\desktop\grouper.ps1
```
Let me know how you go.

**Comment by l0ss** [comment]
Just realised I typed it wrong in the README. Fixing that now.

**Comment by l0ss** [comment]
problem in documentation - reopen if specifying path properly doesn't fix.
