### ISSUE TITLE
Filter for "ClearTextPassword" policy setting

### ISSUE THREAD

**Issue by cryps1s** [l0ss/Grouper#7]
**Issue:** There is a false positive which occurs if the ```ClearTextPassword``` setting is defined but the SettingBoolean is set to ```false```. In this configuration, there is no value to this information for an attacker, and I believe it can be safely ignored. 

Output:
```
Get-GPOAccountSettings - All Policy
###################################
SettingBoolean                 false
Name                           ClearTextPassword
Type                           Password
```

**Comment by l0ss** [comment]
Fix'd
